imports:
    - { resource: config.yml }

framework:
   validation:
       cache: validator.mapping.cache.doctrine.apc
   serializer:
       cache: serializer.mapping.cache.apc

# doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

nelmio_api_doc:
    cache:
        enabled: true

monolog:
    handlers:
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
            max_files: 60
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        syslog:
            type:  syslog
            level: info
        console:
            type:  console
